const lang = {
  en: {
    search: "Search",
    signUp: "Sign Up",
    login: "Login",
    name: "Name",
    email: "Email",
    password: "Password",
    alreadyRegistered: "Already Registered?",
    searchGPT: "Search GPT",
    signOut: "Sign Out",
    upcoming: "Upcoming",
    topRated: "Top Rated",
    comedy: "Comedy",
    popular: "Popular",
    nowPlaying: "Now Playing",
    whatToWatch: "What do you like to watch?",
    homePage: "Home Page",
    searching: "Searching...",
  },
  hindi: {
    search: "खोज",
    signUp: "साइन अप",
    login: "लॉगिन",
    name: "नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    alreadyRegistered: "पहले से पंजीकृत?",
    searchGPT: "GPT खोजें",
    signOut: "साइन आउट",
    upcoming: "आगामी",
    topRated: "सर्वश्रेष्ठ रेटेड",
    comedy: "कॉमेडी",
    popular: "लोकप्रिय",
    nowPlaying: "अब चल रहा है",
    whatToWatch: "आप क्या देखना पसंद करेंगे?",
    homePage: "मुख्य पृष्ठ",
    searching: "खोज हो रही है...",
  },
  jap: {
    search: "検索",
    signUp: "サインアップ",
    login: "ログイン",
    name: "名前",
    email: "Eメール",
    password: "パスワード",
    alreadyRegistered: "すでに登録済みですか？",
    searchGPT: "GPT検索",
    signOut: "サインアウト",
    upcoming: "近日公開",
    topRated: "トップレート",
    comedy: "コメディ",
    popular: "人気",
    nowPlaying: "上映中",
    whatToWatch: "何を見たいですか？",
    homePage: "ホームページ",
    searching: "検索中...",
  },
  spanish: {
    search: "buscar",
    signUp: "Regístrate",
    login: "Iniciar sesión",
    name: "Nombre",
    email: "Correo electrónico",
    password: "Contraseña",
    alreadyRegistered: "¿Ya registrado?",
    searchGPT: "Buscar GPT",
    signOut: "Cerrar sesión",
    upcoming: "Próximamente",
    topRated: "Mejor valorados",
    comedy: "Comedia",
    popular: "Popular",
    nowPlaying: "En cartelera",
    whatToWatch: "¿Qué te gustaría ver?",
    homePage: "Página principal",
    searching: "Buscando...",
  },
};

export default lang;
